---
- name: reload kvm module
  ansible.builtin.debug:
    msg: "KVM module configuration updated. A system reboot or manual module reload is required for changes to take effect. Run 'modprobe -r kvm_intel && modprobe kvm_intel' (Intel) or 'modprobe -r kvm_amd && modprobe kvm_amd' (AMD)"
